### ISSUE TITLE
Potential issue while upgrading from .25.1 to .25.2

### ISSUE THREAD

**Issue by thomaslima** [klayoutmatthias/klayout#102]
A labmate reported that when he installed the new klayout, he got that “Got an empty string where a real number was expected” [exception](https://github.com/klayoutmatthias/klayout/issues/85#issuecomment-372336582).

This could be solved by deleting the `~/.klayout/klayoutrc` file.

Can anyone help upgrade from a clean .25.1 to a .25.2 to check whether this will be a major issue for end users? Otherwise, more in the long term, we have to change klayout code so that it's failsafe with regards to "corrupted" klayoutrc.

**Comment by klayoutmatthias** [comment]
Hi Thomas,

I will try to reproduce the issue.

Matthias

**Comment by thomaslima** [comment]
Don't try too hard. Might be a false alarm, as he at some point installed a dev version.

**Comment by klayoutmatthias** [comment]
No, not a false alarm. A real issue. Thanks a lot for testing!!! 

I did not see that myself (yet) because I did not try to upgrade (yet).

I have fixed that plus made the application safe against failure when reading the config. Config errors are reported but ignored otherwise.

Thanks again and best regards,

Matthias

**Comment by thomaslima** [comment]
Thank you for figuring this out. We really appreciate it.

LG
Thomas
