### ISSUE TITLE
Error in cell.fill_region

### ISSUE THREAD

**Issue by EmilKleijn** [klayoutmatthias/klayout#134]
In a Ruby script I am running, I use the fill_region function to add tiling. I have now encountered a problematic file that generates the following error in KLayout v0.25.3:
Internal error: ../../../src/db/db/dbPolygonGenerators.cc:303 m_open.emtpy () was not true in Cell:fill_region

The fill_region command runs sucessfully in v0.24.8

Required files for reproducing the issue:
[Files.zip](https://github.com/klayoutmatthias/klayout/files/2123269/Files.zip)

Includes the export script, the fill cell, and the problematic cell.

Regards

**Comment by klayoutmatthias** [comment]
Thanks a lot for the test case. I will look into this.

Matthias

**Comment by klayoutmatthias** [comment]
Hi,

I'm able to reproduce this issue and isolate the internal data which cause this error. Internal a big polygon with zero-width spikes is generated. I assume due to some implicit normalization these got deleted in 0.24.x.

I'll try to provide a fix this this. I'm afraid there is no simple workaround currently except using 0.24.

Best regards,

Matthias

**Comment by EmilKleijn** [comment]
Hi Matthias,

Thanks for looking into this! I'm glad you can reproduce the issue.

Regards,
Emil
