### ISSUE TITLE
Wrong font is used

### ISSUE THREAD

**Issue by olcc** [klayoutmatthias/klayout#148]
Hello,  [cf. https://www.klayout.de/forum/discussion/1098/problem-with-fonts-bug]

I recently learned how to build and use a custom font thanks to the documentation page: https://www.klayout.de/doc/about/basic_lib.html#h2-44

I created a font called "MY_FONT" (in file "my_font.gds") and I used it successfully in a test file ("font_test.gds"). This means that I could insert a PCell, choose my custom font from the menu, and see that the graphic display is indeed using MY_FONT, because it is clearly different from the standard font. This worked as expected.

PROBLEM:

When I reopen the file, the font is back to the standard font!
- The PCell parameter "Font" still indicates "MY_FONT", but it is not using that font. It uses instead the standard font.
- This looks like a bug, can you test or tell what it wrong?

Best regards,

[problem_with_fonts.zip](https://github.com/klayoutmatthias/klayout/files/2235881/problem_with_fonts.zip)

--
Olivier (Klayout version 0.25.3)

**Comment by klayoutmatthias** [comment]
Hi Olivier,

the issue is closely related to #139 where the same happened with libraries. The fix is very similar and will go into 0.25.4. The reason is that the font system is initialized after files have been loaded from the command line. Files that are loaded later don't have this issue.

So the workaround until 0.25.4 is simply: open the file with File/Open or File/Recent rather than from the command line (same as double-click on the file icon). 

BTW: you can pull a pre-release build of 0.25.4 from http://www.klayout.org/downloads/staging/windows/klayout-0.25.4-win32-install.exe or http://www.klayout.org/downloads/staging/windows/klayout-0.25.4-win64-install.exe if you're on Windows. Please allow about one hour from the commit to the build.

Thanks for reporting this issue,

Matthias
